# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "vmd" "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # Boot Drive
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4b791955-2543-431e-b427-b36775e1f663";
      fsType = "btrfs";
      options = [ "subvol=@" "ssd" "compress=zstd" "discard=async" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/4b791955-2543-431e-b427-b36775e1f663";
      fsType = "btrfs";
      options = [ "subvol=@home" "ssd" "compress=zstd" "discard=async" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/49ED-F7CC";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/7479c4e7-d41c-4f2e-8ea1-199eae684ad2"; }
    ];

  # Sata SSD Array


  # Sata HDD Array


  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
